// license-header java merge-point
//
// Generated by: MetafacadeLogicImpl.vsl in andromda-meta-cartridge.
package org.andromda.cartridges.webservice.metafacades;

/**
 * 
 * MetafacadeLogic implementation for org.andromda.cartridges.webservice.metafacades.OublFacadeClientOperation.
 *
 * @see org.andromda.cartridges.webservice.metafacades.OublFacadeClientOperation
 */
public class OublFacadeClientOperationLogicImpl
    extends OublFacadeClientOperationLogic
{
    private static final long serialVersionUID = 34L;
    /**
     * Public constructor for OublFacadeClientOperationLogicImpl
     * @see org.andromda.cartridges.webservice.metafacades.OublFacadeClientOperation
     */
    public OublFacadeClientOperationLogicImpl (Object metaObject, String context)
    {
        super(metaObject, context);
    }

    /**
     * 
     * @see org.andromda.cartridges.webservice.metafacades.OublFacadeClientOperation#getOublFacadeClientUrl()
     */
    protected String handleGetOublFacadeClientUrl()
    {
        // TODO put your implementation here.
        return null;
    }
}